import { useMemo, useRef, useState, type ElementType } from 'react';
import { Link, useLocation } from 'wouter';
import {
  ArrowRight, BarChart3, Check, ChevronDown, FileVideo2, Filter, Info, Search,
  ShieldAlert, ShieldCheck, Sparkles, Upload, Users, Video, Activity,
} from 'lucide-react';
import {
  Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line,
  ResponsiveContainer, Tooltip, XAxis, YAxis,
} from 'recharts';
import { cvResults, methodology, models, players, poseFeatures, project, svmInputs, type PlayerReport } from '@/data/research';
import { PageIntro } from '@/components/AppShell';

const pct = (n: number) => `${n.toFixed(2)}%`;
const modelColors = ['#77928a', '#7c98aa', '#55c890', '#a48c71', '#9683a9'];
const chartStyle = { background: '#171e27', border: '1px solid #303b47', borderRadius: 10, color: '#e1e8e4', fontSize: 11 };
const selectedModel = models.find((model) => model.name === project.selectedModel)!;

function PanelTitle({ title, note, extra }: { title: string; note?: string; extra?: React.ReactNode }) {
  return <div className="mb-5 flex items-start justify-between gap-4"><div><h3 className="text-[13px] font-bold text-foreground">{title}</h3>{note && <p className="mt-1 text-[10px] leading-5 text-muted-foreground">{note}</p>}</div>{extra}</div>;
}
function Metric({ label, value, detail, tone = 'green', icon: Icon = Activity }: { label: string; value: string; detail: string; tone?: string; icon?: ElementType }) {
  return <div className="panel group relative overflow-hidden rounded-xl p-4 sm:p-5" data-testid={`metric-${label.toLowerCase().replaceAll(' ', '-')}`}><div className="absolute right-0 top-0 h-20 w-20 translate-x-7 -translate-y-7 rounded-full border border-white/[.035]" /><div className="mb-4 flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">{label}</span><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${tone === 'gold' ? 'bg-accent/10 text-accent' : tone === 'red' ? 'bg-destructive/10 text-destructive' : 'bg-primary/10 text-primary'}`}><Icon size={15} /></span></div><div className="font-display text-[27px] font-bold tracking-[-.04em] text-foreground">{value}</div><div className="mt-2 text-[10px] text-muted-foreground">{detail}</div></div>;
}
function StatusPill({ higher }: { higher: boolean }) {
  return <span className={`inline-flex whitespace-nowrap rounded-md px-2 py-1 text-[9px] font-bold ${higher ? 'bg-accent/10 text-accent' : 'bg-primary/10 text-primary'}`}><span className={`mr-1.5 mt-[3px] h-1.5 w-1.5 rounded-full ${higher ? 'bg-accent' : 'bg-primary'}`} />{higher ? 'Higher-risk screening indication' : 'Lower-risk screening indication'}</span>;
}
function Disclaimer({ children = project.disclaimer }: { children?: string }) {
  return <div className="flex items-start gap-2.5 rounded-lg border border-accent/20 bg-accent/[.055] px-3.5 py-3 text-[10px] leading-5 text-accent/90" data-testid="text-screening-disclaimer"><Info size={14} className="mt-0.5 shrink-0" />{children}</div>;
}

export function DashboardPage() {
  const risk = players.filter((p) => p.result.startsWith('Higher')).length;
  const lower = players.length - risk;
  return <div>
    <PageIntro eyebrow="Research overview / 01" title="Movement, measured." description="A clear view of the anonymized screening cohort and the two complementary analysis modules." />
    <section className="relative mb-5 overflow-hidden rounded-2xl border border-[#2c3c38] bg-[#131e1c] p-5 sm:p-7 lg:p-8" data-testid="dashboard-overview">
      <div className="pitch-grid absolute inset-0 opacity-40" /><div className="absolute -right-10 -top-24 h-72 w-72 rounded-full border border-primary/[.08]" /><div className="absolute -right-2 -top-16 h-56 w-56 rounded-full border border-primary/[.08]" />
      <div className="relative grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end">
        <div><div className="mb-4 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-primary"><span className="h-1.5 w-1.5 rounded-full bg-primary status-dot" /> Academic research prototype</div><h2 className="max-w-[680px] font-display text-[30px] font-bold leading-[1.08] tracking-[-.045em] text-[#edf4f0] sm:text-[42px]">Cricket movement.<br /><span className="text-primary">Screened with care.</span></h2><p className="mt-4 max-w-lg text-[12px] leading-6 text-[#9aa9a2]">Structured-data screening and computer-vision movement analysis—two complementary views, presented separately.</p>
          <div className="mt-6 flex flex-wrap gap-2"><Link href="/structured-screening" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-[10px] font-extrabold text-[#10231a] transition hover:bg-[#68d8a3]" data-testid="link-open-screening">Explore screening <ArrowRight size={13} /></Link><Link href="/video-analysis" className="inline-flex items-center gap-2 rounded-lg border border-[#43534c] px-4 py-2.5 text-[10px] font-bold text-[#d6e3dc] hover:bg-white/[.05]" data-testid="link-open-video">Movement module <ArrowRight size={13} /></Link></div>
        </div>
        <div className="grid grid-cols-2 gap-3">
          {[{ title: '01 / STRUCTURED DATA', line: 'SVM screening', sub: 'Workload & fitness inputs', icon: ShieldCheck, color: 'text-primary' }, { title: '02 / COMPUTER VISION', line: 'YOLOv8n + Pose', sub: 'Detection & movement features', icon: Video, color: 'text-[#82b9d0]' }].map((m) => <div className="rounded-xl border border-white/[.08] bg-black/15 p-3.5 sm:p-4" key={m.title}><m.icon className={`${m.color} mb-4`} size={18} /><div className="text-[8px] font-bold tracking-[.12em] text-muted-foreground">{m.title}</div><div className="mt-1.5 text-[12px] font-bold text-foreground">{m.line}</div><div className="mt-1 text-[9px] text-muted-foreground">{m.sub}</div></div>)}
        </div>
      </div>
    </section>
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">
      <Metric label="Players screened" value={String(project.athleteCount)} detail="Anonymized dataset IDs" icon={Users} />
      <Metric label="Lower-risk indications" value={String(lower)} detail="Structured screening outputs" icon={ShieldCheck} />
      <Metric label="Higher-risk indications" value={String(risk)} detail="Players 020 and 029" tone="gold" icon={ShieldAlert} />
      <Metric label="Models evaluated" value={String(models.length)} detail="Structured-data comparison" icon={BarChart3} />
    </div>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <section className="panel rounded-xl p-4 sm:p-5"><PanelTitle title="Structured model snapshot" note="Held-out test metrics · percentage" extra={<Link href="/model-comparison" className="flex items-center gap-1 text-[10px] font-bold text-primary" data-testid="link-model-comparison">Full comparison <ArrowRight size={12} /></Link>} />
        <div className="mb-3 flex gap-4 text-[9px] text-muted-foreground"><span><i className="mr-1.5 inline-block h-2 w-2 rounded-sm bg-[#48695b]" />Recall</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-sm bg-primary" />F1-score</span></div>
        <div className="h-[245px] w-full" data-testid="chart-dashboard-models"><ResponsiveContainer width="100%" height="100%"><BarChart data={models} margin={{ top: 3, right: 10, bottom: 0, left: -20 }} barGap={3}><CartesianGrid stroke="#26313a" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="name" tick={{ fill: '#819098', fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#687983', fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={chartStyle} formatter={(value: number) => `${value}%`} /><Bar dataKey="recall" name="Recall" fill="#48695b" radius={[3,3,0,0]} /><Bar dataKey="f1" name="F1-score" fill="#55c890" radius={[3,3,0,0]} /></BarChart></ResponsiveContainer></div>
      </section>
      <section className="panel flex flex-col rounded-xl p-5"><div className="mb-4 flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><Sparkles size={15} /></span><span className="text-[10px] font-bold uppercase tracking-[.12em] text-primary">Selected candidate</span></div><div className="font-display text-[34px] font-bold tracking-[-.04em]">{project.selectedModel}</div><p className="mt-1 text-[10px] text-muted-foreground">High-sensitivity screening candidate</p>
        <div className="my-5 grid grid-cols-2 gap-3"><div className="rounded-lg bg-secondary/70 p-3"><div className="text-[9px] uppercase tracking-wider text-muted-foreground">Recall</div><div className="mt-1.5 font-mono-data text-[21px] text-primary">{pct(selectedModel.recall)}</div></div><div className="rounded-lg bg-secondary/70 p-3"><div className="text-[9px] uppercase tracking-wider text-muted-foreground">F1 score</div><div className="mt-1.5 font-mono-data text-[21px] text-primary">{pct(selectedModel.f1)}</div></div></div>
        <p className="border-l-2 border-primary/60 pl-3 text-[10px] leading-5 text-muted-foreground">{project.selectionStatement}</p><div className="mt-auto pt-5"><Disclaimer /></div>
      </section>
    </div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2">
      <section className="panel rounded-xl p-5"><PanelTitle title="Cohort screening indications" note="As supplied in the anonymized final screening report" />
        <div className="flex items-center gap-5"><div className="flex h-28 w-28 items-center justify-center rounded-full border-[9px] border-primary/80 shadow-[inset_0_0_20px_rgba(85,200,144,.08)]"><div className="text-center"><div className="font-display text-[26px] font-bold">{project.athleteCount}</div><div className="text-[8px] uppercase tracking-wider text-muted-foreground">players</div></div></div><div className="space-y-3 text-[10px]"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-sm bg-primary" /><span className="text-muted-foreground">Lower-risk indication</span><b className="ml-auto font-mono-data text-foreground">{lower}</b></div><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-sm bg-accent" /><span className="text-muted-foreground">Higher-risk indication</span><b className="ml-auto font-mono-data text-foreground">{risk}</b></div><Link href="/players" className="mt-1 inline-flex items-center gap-1 font-bold text-primary" data-testid="link-cohort-players">Browse player reports <ArrowRight size={12} /></Link></div></div>
      </section>
      <section className="panel rounded-xl p-5"><PanelTitle title="Computer-vision evaluation" note="Detection results from the validated training environment" />
        <div className="grid grid-cols-2 gap-3">{cvResults.map((r) => <div key={r.model} className="rounded-lg border border-border/70 p-3"><div className="text-[9px] font-bold text-foreground">{r.model}</div><div className="mt-3 grid grid-cols-2 gap-y-2 text-[9px] text-muted-foreground"><span>Precision</span><b className="text-right font-mono-data text-foreground">{r.precision}%</b><span>Recall</span><b className="text-right font-mono-data text-foreground">{r.recall}%</b><span>mAP50</span><b className="text-right font-mono-data text-primary">{r.map50}%</b><span>mAP50-95</span><b className="text-right font-mono-data text-foreground">{r.map5095}%</b></div></div>)}</div>
      </section>
    </div>
  </div>;
}

export function PlayersPage() {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [sortHigh, setSortHigh] = useState(true);
  const filtered = useMemo(() => players.filter((p) => p.id.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'higher' ? p.result.startsWith('Higher') : p.result.startsWith('Lower')))).sort((a, b) => sortHigh ? a.numericId - b.numericId : b.numericId - a.numericId), [query, filter, sortHigh]);
  return <div>
    <PageIntro eyebrow="Cohort / 30 anonymized IDs" title="Player screening" description="Search the final per-player report. Workload, fitness inputs, screening results and contextual injury history are displayed as supplied." />
    <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div className="relative w-full sm:max-w-[290px]"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search player ID…" className="h-10 w-full rounded-lg border border-border bg-card pl-9 pr-3 text-[11px] outline-none placeholder:text-muted-foreground focus:border-primary/60" data-testid="input-player-search" /></div>
      <div className="flex gap-2"><label className="flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-3 text-[10px] text-muted-foreground"><Filter size={13} /><select value={filter} onChange={(e) => setFilter(e.target.value)} className="bg-transparent text-foreground outline-none" data-testid="select-risk-filter"><option value="all">All indications</option><option value="lower">Lower-risk</option><option value="higher">Higher-risk</option></select></label><button onClick={() => setSortHigh((s) => !s)} className="h-10 rounded-lg border border-border bg-card px-3 text-[10px] font-semibold text-muted-foreground hover:text-foreground" data-testid="button-sort-players">ID {sortHigh ? 'ascending' : 'descending'}</button></div>
    </div>
    <div className="panel overflow-hidden rounded-xl">
      <div className="flex items-center justify-between border-b border-border px-4 py-3"><div className="text-[10px] font-bold text-foreground">Screening report <span className="ml-2 font-normal text-muted-foreground">{filtered.length} of {players.length} players</span></div><div className="text-[9px] text-muted-foreground">Report date · 2018-04-30</div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-[10px]"><thead className="bg-white/[.025] text-[8px] uppercase tracking-[.12em] text-muted-foreground"><tr>{['Player ID','Workload','Groin squeeze','Hip mobility','SVM positive-class probability','Threshold','Screening result','Historical injury record',''].map((h) => <th className="px-4 py-3 font-bold" key={h}>{h}</th>)}</tr></thead>
        <tbody>{filtered.map((p) => <tr key={p.id} className="border-t border-border/70 transition-colors hover:bg-white/[.025]" data-testid={`row-player-${p.numericId}`}><td className="px-4 py-3"><Link href={`/player-details?player=${p.numericId}`} className="font-bold text-foreground hover:text-primary" data-testid={`link-player-${p.numericId}`}>{p.id}</Link><div className="mt-1 text-[8px] text-muted-foreground">Dataset ID · {String(p.numericId).padStart(3,'0')}</div></td><td className="px-4 py-3 font-mono-data">{p.workload}</td><td className="px-4 py-3 font-mono-data">{p.groin}</td><td className="px-4 py-3 font-mono-data">{p.hip}</td><td className={`px-4 py-3 font-mono-data ${p.result.startsWith('Higher') ? 'text-accent' : 'text-foreground'}`}>{p.probability}</td><td className="px-4 py-3 font-mono-data text-muted-foreground">{p.threshold}</td><td className="px-4 py-3"><StatusPill higher={p.result.startsWith('Higher')} /></td><td className="px-4 py-3 text-muted-foreground">{p.injuryRecords} records</td><td className="px-4 py-3"><Link className="text-primary hover:text-primary/70" href={`/player-details?player=${p.numericId}`} data-testid={`link-report-${p.numericId}`}><ArrowRight size={14} /></Link></td></tr>)}</tbody>
      </table></div>
      {filtered.length === 0 && <div className="p-12 text-center"><div className="mx-auto mb-3 flex h-10 w-10 items-center justify-center rounded-full bg-secondary text-muted-foreground"><Search size={17} /></div><div className="text-[12px] font-bold">No matching player IDs</div><div className="mt-1 text-[10px] text-muted-foreground">Adjust your search or screening filter.</div></div>}
    </div>
    <p className="mt-3 text-[9px] leading-5 text-muted-foreground">Historical injury information is contextual only and is not an input to the current SVM. Player IDs are anonymized research dataset identifiers.</p>
  </div>;
}

function ProfileReport({ player }: { player: PlayerReport }) {
  const facts = [
    ['Analysis date', player.date], ['Total records', player.totalRecords.toLocaleString()], ['Historical injury records', player.injuryRecords.toString()],
    ['Historical injury status', player.historicalStatus], ['Game workload', player.workload], ['Groin squeeze', player.groin], ['Hip mobility', player.hip],
  ];
  return <div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]">
    <section className="panel rounded-xl p-5 sm:p-6"><div className="flex items-start justify-between"><div><div className="text-[9px] font-bold uppercase tracking-[.15em] text-muted-foreground">ANONYMIZED PLAYER</div><h3 className="mt-2 font-display text-[27px] font-bold tracking-tight">{player.id}</h3><p className="mt-1 text-[10px] text-muted-foreground">Dataset record · {player.date}</p></div><div className="flex h-12 w-12 items-center justify-center rounded-xl border border-border bg-secondary text-primary"><Users size={21} /></div></div>
      <div className="my-5 flex items-center justify-between rounded-xl border border-border bg-background/60 p-4"><div><div className="text-[9px] uppercase tracking-wider text-muted-foreground">SVM positive-class probability</div><div className="mt-1 font-mono-data text-[27px] font-medium">{player.probability}</div></div><div className="text-right"><div className="text-[9px] uppercase tracking-wider text-muted-foreground">Threshold</div><div className="mt-1 font-mono-data text-[16px]">{player.threshold}</div></div></div>
      <div className="mb-2 text-[9px] font-bold uppercase tracking-[.12em] text-muted-foreground">SVM Screening Result</div><div className={`mb-5 flex items-center gap-2 rounded-lg px-3 py-3 text-[11px] font-bold ${player.result.startsWith('Higher') ? 'bg-accent/10 text-accent' : 'bg-primary/10 text-primary'}`}>{player.result.startsWith('Higher') ? <ShieldAlert size={15} /> : <ShieldCheck size={15} />}{player.result}</div>
      <Disclaimer />
    </section>
    <section className="panel rounded-xl p-5 sm:p-6"><PanelTitle title="Player report" note="Verified final per-player screening report" />
      <div className="grid gap-x-8 sm:grid-cols-2">{facts.map(([label, value]) => <div key={label} className="flex min-h-[58px] items-center justify-between gap-4 border-b border-border/70 py-3"><span className="text-[10px] text-muted-foreground">{label}</span><span className="text-right text-[10px] font-semibold text-foreground">{value}</span></div>)}</div>
      <div className="mt-5 rounded-lg border border-border bg-background/40 p-4"><div className="mb-3 flex items-center gap-2 text-[10px] font-bold text-foreground"><Info size={13} className="text-accent" />Contextual information</div><p className="text-[10px] leading-5 text-muted-foreground">Historical injury records are shown as context in this report. They are not an input feature for the current SVM screening model.</p></div>
      <div className="mt-5"><div className="mb-3 text-[9px] font-bold uppercase tracking-[.13em] text-muted-foreground">SVM input features</div><div className="flex flex-wrap gap-2">{svmInputs.map((input) => <span className="rounded-md border border-border bg-secondary/50 px-2.5 py-1.5 font-mono-data text-[9px] text-primary" key={input}>{input}</span>)}</div></div>
    </section>
  </div>;
}
export function PlayerDetailsPage() {
  const [, setLocation] = useLocation();
  const params = new URLSearchParams(window.location.search);
  const initial = Math.min(30, Math.max(1, Number(params.get('player')) || 20));
  const [selected, setSelected] = useState(initial);
  const player = players[selected - 1];
  function choose(value: number) { setSelected(value); setLocation(`/player-details?player=${value}`); }
  return <div><PageIntro eyebrow="Individual record / anonymized" title="Player details" description="A selectable report showing screening output alongside contextual player history. No clinical interpretation is made." action={<label className="flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-3 text-[10px] text-muted-foreground"><span>Player</span><select value={selected} onChange={(e) => choose(Number(e.target.value))} className="bg-transparent font-semibold text-foreground outline-none" data-testid="select-player-report">{players.map((p) => <option value={p.numericId} key={p.id}>{p.id}</option>)}</select><ChevronDown size={12} /></label>} />
    <div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Total records',player.totalRecords.toString()],['Historical injury records',player.injuryRecords.toString()],['Report date',player.date],['Screening threshold',player.threshold]].map(([label,value]) => <div className="panel rounded-lg p-3.5" key={label}><div className="text-[9px] text-muted-foreground">{label}</div><div className="mt-1.5 text-[13px] font-bold text-foreground">{value}</div></div>)}</div>
    <ProfileReport player={player} />
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="text-[9px] text-muted-foreground">Report values shown as supplied; history is contextual and not a model input.</div><div className="flex gap-2"><button disabled={selected <= 1} onClick={() => choose(selected - 1)} className="rounded-lg border border-border px-3 py-2 text-[10px] font-bold text-muted-foreground disabled:opacity-35" data-testid="button-previous-player">Previous</button><button disabled={selected >= 30} onClick={() => choose(selected + 1)} className="rounded-lg border border-border px-3 py-2 text-[10px] font-bold text-muted-foreground disabled:opacity-35" data-testid="button-next-player">Next player <ArrowRight size={12} className="ml-1 inline" /></button></div></div>
  </div>;
}

function ModelChart({ focus }: { focus?: string }) {
  return <div className="h-[290px] w-full" data-testid={focus ? 'chart-screening-metrics' : 'chart-model-metrics'}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={models} margin={{ top: 10, right: 12, bottom: 0, left: -18 }}><CartesianGrid stroke="#26313a" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="name" tick={{ fill: '#87949b', fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#687983', fontSize: 9 }} axisLine={false} tickLine={false} domain={[0,100]} /><Tooltip contentStyle={chartStyle} formatter={(v: number) => `${v}%`} /><Legend wrapperStyle={{ fontSize: 10, color: '#9caab0' }} /><Bar dataKey="accuracy" name="Accuracy" fill="#33433e" radius={[3,3,0,0]} /><Line dataKey="recall" name="Recall" stroke="#55c890" strokeWidth={2.5} dot={{ r: 3, fill: '#55c890' }} /><Line dataKey="f1" name="F1-score" stroke="#e4ba5b" strokeWidth={2} dot={{ r: 3, fill: '#e4ba5b' }} /></ComposedChart></ResponsiveContainer></div>;
}
function ModelsTable() {
  return <div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-[10px]"><thead className="text-[8px] uppercase tracking-[.13em] text-muted-foreground"><tr>{['Model','Accuracy','Precision','Recall','F1'].map((h)=><th className="px-3 py-3 font-bold" key={h}>{h}</th>)}</tr></thead><tbody>{models.map((m,i)=><tr key={m.name} className={`border-t border-border/70 ${m.name==='SVM'?'bg-primary/[.045]':''}`}><td className="px-3 py-3 font-bold text-foreground">{m.name}{m.name==='SVM'&&<span className="ml-2 rounded bg-primary/10 px-1.5 py-1 text-[8px] text-primary">SELECTED</span>}</td><td className="px-3 py-3 font-mono-data">{pct(m.accuracy)}</td><td className="px-3 py-3 font-mono-data">{pct(m.precision)}</td><td className={`px-3 py-3 font-mono-data ${m.name==='SVM'?'font-bold text-primary':''}`}>{pct(m.recall)}</td><td className={`px-3 py-3 font-mono-data ${m.name==='SVM'?'font-bold text-accent':''}`}>{pct(m.f1)}</td></tr>)}</tbody></table></div>;
}
export function StructuredScreeningPage() {
  const screeningStats = [
    ['Recall', pct(selectedModel.recall), 'Highest in comparison'],
    ['Accuracy', pct(selectedModel.accuracy), 'Held-out test'],
    ['Precision', pct(selectedModel.precision), 'Low precision'],
    ['F1-score', pct(selectedModel.f1), 'Highest in comparison'],
    ['Threshold', `${project.threshold.toFixed(2)}%`, 'Screening threshold'],
  ];
   return <div><PageIntro eyebrow="Structured data / model screening" title="Structured screening" description="SVM held-out test performance and the exact model-selection rationale. The candidate prioritizes sensitivity, not overall superiority." />
    <div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-5">{screeningStats.map(([label,value,note],i)=><div key={label} className="panel rounded-xl p-4"><div className="text-[9px] font-bold uppercase tracking-[.12em] text-muted-foreground">{label}</div><div className={`mt-2 font-mono-data text-[22px] ${i===0||i===3?'text-primary':'text-foreground'}`}>{value}</div><div className="mt-1 text-[9px] text-muted-foreground">{note}</div></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="panel rounded-xl p-5"><PanelTitle title="Five-model metric comparison" note="Percentage · provided held-out test performance" /><ModelChart focus="screening" /></section><section className="panel rounded-xl p-5"><PanelTitle title="Screening candidate rationale" note="SVM selected for high-sensitivity screening" /><div className="space-y-3"><div className="rounded-lg border border-primary/20 bg-primary/[.055] p-3.5"><div className="mb-1.5 text-[9px] font-bold uppercase tracking-wider text-primary">Recall lead</div><div className="text-[11px] font-semibold">Highest recall in the supplied five-model comparison.</div><p className="mt-1 text-[9px] text-muted-foreground">96.15% on the supplied held-out test set.</p></div><div className="rounded-lg border border-accent/20 bg-accent/[.045] p-3.5"><div className="mb-1.5 text-[9px] font-bold uppercase tracking-wider text-accent">F1 lead</div><div className="text-[11px] font-semibold">Highest F1-score in the supplied five-model comparison.</div><p className="mt-1 text-[9px] text-muted-foreground">10.66% balances precision and recall for this evaluation.</p></div><div className="rounded-lg bg-secondary/55 p-3.5 text-[10px] leading-5">{project.lowPrecision}<br /><span className="text-muted-foreground">Read scores within the context of the evaluation dataset.</span></div><Disclaimer /></div></section></div>
    <section className="panel mt-5 rounded-xl p-5"><PanelTitle title="Performance detail" note="Exact supplied metrics · percentages" /><ModelsTable /></section>
  </div>;
}
export function ModelComparisonPage() {
  const [metric, setMetric] = useState<'accuracy'|'precision'|'recall'|'f1'>('recall');
  const label = {accuracy:'Accuracy',precision:'Precision',recall:'Recall',f1:'F1-score'}[metric];
  return <div><PageIntro eyebrow="Evaluation / five models" title="Model comparison" description="Compare the supplied structured-data results across accuracy, precision, recall and F1. Accuracy alone does not determine candidate selection." action={<label className="flex h-10 items-center gap-2 rounded-lg border border-border bg-card px-3 text-[10px] text-muted-foreground"><span>Chart metric</span><select value={metric} onChange={(e)=>setMetric(e.target.value as typeof metric)} className="bg-transparent font-semibold text-foreground outline-none" data-testid="select-chart-metric"><option value="recall">Recall</option><option value="f1">F1-score</option><option value="precision">Precision</option><option value="accuracy">Accuracy</option></select></label>} />
    <div className="mb-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="panel rounded-xl p-5"><PanelTitle title={`${label} by model`} note="Select a metric to inspect the distribution · %" /><div className="h-[310px]" data-testid="chart-comparison-active"><ResponsiveContainer width="100%" height="100%"><BarChart data={models} margin={{top:10,right:10,bottom:0,left:-15}}><CartesianGrid stroke="#26313a" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="name" tick={{fill:'#87949b',fontSize:9}} axisLine={false} tickLine={false}/><YAxis tick={{fill:'#687983',fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={chartStyle} formatter={(v:number)=>`${v}%`}/><Bar dataKey={metric} name={label} radius={[4,4,0,0]}>{models.map((m,i)=><Cell key={m.name} fill={m.name==='SVM'?'#55c890':modelColors[i]} />)}</Bar></BarChart></ResponsiveContainer></div></section>
      <section className="panel rounded-xl p-5"><PanelTitle title="Detection model results" note="Validated computer-vision results · separate module" /><div className="overflow-x-auto"><table className="w-full min-w-[440px] text-left text-[9px]"><thead className="text-[8px] uppercase tracking-wider text-muted-foreground"><tr>{['Model','Precision','Recall','mAP50','mAP50–95'].map(x=><th key={x} className="px-2 py-3">{x}</th>)}</tr></thead><tbody>{cvResults.map(r=><tr key={r.model} className="border-t border-border/70"><td className="px-2 py-3 font-semibold text-foreground">{r.model}</td><td className="px-2 py-3 font-mono-data">{r.precision}%</td><td className="px-2 py-3 font-mono-data">{r.recall}%</td><td className="px-2 py-3 font-mono-data text-primary">{r.map50}%</td><td className="px-2 py-3 font-mono-data">{r.map5095}%</td></tr>)}</tbody></table></div><div className="mt-4 rounded-lg border border-border bg-background/40 p-3 text-[9px] leading-5 text-muted-foreground">Computer-vision detection metrics describe object detection only. They are not injury predictions or screening probabilities.</div></section></div>
    <section className="panel rounded-xl p-5"><PanelTitle title="Structured-data model performance" note="Exact metrics provided for the five evaluated models" /><ModelsTable /></section>
    <div className="mt-5 flex gap-3 rounded-xl border border-primary/15 bg-primary/[.045] p-4"><span className="mt-0.5 text-primary"><Check size={16}/></span><p className="text-[10px] leading-5 text-muted-foreground">{project.selectionStatement}</p></div>
  </div>;
}

export function VideoAnalysisPage() {
  const [filename,setFilename]=useState('');
  const [drag,setDrag]=useState(false);
  const inputRef=useRef<HTMLInputElement>(null);
  function accept(file?:File){if(file) setFilename(file.name);}
  const steps=['VIDEO INPUT','YOLOv8n OBJECT DETECTION','YOLOv8n-POSE','17 BODY KEYPOINTS','BIOMECHANICAL FEATURE EXTRACTION','MOVEMENT ANALYSIS'];
   return <div><PageIntro eyebrow="Computer vision / movement" title="Video analysis" description="The intended computer-vision workflow is shown here. Local file selection is available; live inference is not simulated." />
    <div className="grid gap-5 xl:grid-cols-[.95fr_1.05fr]"><section className="panel rounded-xl p-5 sm:p-6"><PanelTitle title="Local video input" note="Choose or drop a cricket video file for the intended workflow." />
      <div onDragOver={(e)=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={(e)=>{e.preventDefault();setDrag(false);accept(e.dataTransfer.files[0]);}} className={`flex min-h-[226px] flex-col items-center justify-center rounded-xl border border-dashed px-5 text-center transition-colors ${drag?'border-primary bg-primary/[.06]':'border-border bg-background/35'}`} data-testid="upload-dropzone">
        <input ref={inputRef} type="file" accept="video/*" className="hidden" onChange={(e)=>accept(e.target.files?.[0])} data-testid="input-video-file" />
        <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-xl border border-border bg-secondary text-primary">{filename?<FileVideo2 size={21}/>:<Upload size={20}/>}</div>
        <div className="text-[12px] font-bold">{filename || 'Drop a video file here'}</div><div className="mt-1 text-[9px] text-muted-foreground">{filename?'Selected locally · no analysis has been run':'or browse files from this device'}</div>
        <button onClick={()=>inputRef.current?.click()} className="mt-4 rounded-lg border border-border bg-card px-4 py-2 text-[10px] font-bold text-foreground hover:bg-secondary" data-testid="button-browse-video">{filename?'Choose another file':'Browse video'}</button>
        <div className="mt-3 text-[8px] text-muted-foreground">Video remains a local file selection in this prototype.</div>
      </div>
      <div className="mt-4 rounded-lg border border-accent/20 bg-accent/[.055] p-3.5"><div className="flex gap-2.5"><Info size={14} className="mt-0.5 shrink-0 text-accent"/><p className="text-[10px] leading-[1.7] text-foreground">Live computer-vision inference requires the trained YOLO model weights. The validated computer-vision results were obtained in the Kaggle training environment.</p></div></div>
    </section>
    <section className="panel rounded-xl p-5 sm:p-6"><PanelTitle title="Analysis workflow" note="Computer-vision movement analysis pipeline" /><div className="space-y-1.5">{steps.map((step,i)=><div className="flex flex-col items-start" key={step}><div className={`flex min-h-[39px] w-full items-center gap-3 rounded-lg border px-3 ${i===0||i===steps.length-1?'border-primary/25 bg-primary/[.055]':'border-border bg-background/35'}`}><span className={`flex h-5 w-5 items-center justify-center rounded-md font-mono-data text-[8px] ${i===0||i===steps.length-1?'bg-primary/15 text-primary':'bg-secondary text-muted-foreground'}`}>{String(i+1).padStart(2,'0')}</span><span className="text-[9px] font-bold tracking-[.08em] text-foreground">{step}</span></div>{i<steps.length-1&&<div className="ml-[22px] h-2 border-l border-dashed border-primary/40" />}</div>)}</div>
      <div className="mt-5 border-t border-border pt-4"><div className="mb-3 text-[9px] font-bold uppercase tracking-[.14em] text-muted-foreground">Biomechanical features</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{poseFeatures.map((feature,i)=><div className="rounded-lg border border-border bg-background/35 p-2.5" key={feature}><div className="mb-2 font-mono-data text-[8px] text-primary">F{i+1}</div><div className="text-[9px] font-semibold text-foreground">{feature}</div></div>)}</div><p className="mt-3 text-[9px] text-muted-foreground">Pose model: YOLOv8n-Pose · 17 COCO keypoints</p></div>
    </section></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Detection','YOLOv8n','Cricket object detection'],['Pose','YOLOv8n-Pose','17 COCO keypoints'],['Output','Movement features','No injury probability generated']].map(([label,title,sub])=><div key={label} className="panel flex items-start gap-3 rounded-xl p-4"><span className="rounded-lg bg-secondary p-2 text-primary"><Activity size={15}/></span><div><div className="text-[8px] font-bold uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-1 text-[11px] font-bold">{title}</div><div className="mt-1 text-[9px] text-muted-foreground">{sub}</div></div></div>)}</div>
  </div>;
}

export function ArchitecturePage() {
  const module = (title:string, accent:string, items:string[]) => <div className={`rounded-xl border ${accent} p-4 sm:p-5`}><div className="mb-4 flex items-center gap-2 text-[9px] font-extrabold tracking-[.15em]"><span className="h-2 w-2 rounded-sm bg-current"/>{title}</div><div className="space-y-2">{items.map((x,i)=><div className="rounded-lg border border-border/70 bg-background/55 px-3 py-2.5 text-[10px] font-semibold" key={x}><span className="mr-2 font-mono-data text-muted-foreground">{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div></div>;
  return <div><PageIntro eyebrow="System design / two complementary modules" title="System architecture" description="Separate computational branches produce complementary views and join only in the player report—not in a fused trained model." />
    <section className="panel overflow-hidden rounded-2xl p-4 sm:p-7"><div className="mb-6 flex justify-center"><div className="w-full max-w-[360px] rounded-xl border border-border bg-background/60 p-4 text-center"><div className="text-[8px] font-bold uppercase tracking-[.16em] text-muted-foreground">ANONYMIZED INPUTS</div><div className="mt-2 text-[12px] font-bold">PLAYER RECORD</div><div className="mt-2 flex flex-wrap justify-center gap-1.5">{['Player data','Workload / fitness','Injury history','Video'].map(t=><span className="rounded-md bg-secondary px-2 py-1 text-[8px] text-muted-foreground" key={t}>{t}</span>)}</div></div></div>
      <div className="mx-auto mb-4 h-7 w-px bg-border"/><div className="mx-auto grid max-w-[800px] gap-4 md:grid-cols-2">{module('STRUCTURED-DATA MODULE','border-primary/25 bg-primary/[.025] text-primary',['Structured player / workload data','Five evaluated ML models','SVM screening candidate','Screening result & positive-class score'])}{module('COMPUTER-VISION MODULE','border-[#6a9bb0]/25 bg-[#6a9bb0]/[.035] text-[#87b5c8]',['Cricket image / video input','YOLOv8n object detection','YOLOv8n-Pose · 17 COCO keypoints','Biomechanical features & movement analysis'])}</div>
      <div className="mx-auto mt-4 grid max-w-[800px] grid-cols-2 gap-4"><div className="flex justify-center"><div className="h-7 w-px bg-primary/40"/></div><div className="flex justify-center"><div className="h-7 w-px bg-[#6a9bb0]/40"/></div></div>
      <div className="mx-auto mb-4 flex max-w-[800px] justify-center"><div className="w-full max-w-[390px] rounded-xl border border-accent/25 bg-accent/[.05] p-4 text-center"><div className="text-[8px] font-bold uppercase tracking-[.16em] text-accent">COMPLEMENTARY REPORTING</div><div className="mt-1.5 text-[12px] font-bold">PLAYER REPORT</div><div className="mt-1 text-[9px] text-muted-foreground">Distinct outputs can be reviewed together; no fused trained model is represented.</div></div></div>
      <div className="mx-auto h-6 w-px bg-accent/40"/><div className="mx-auto max-w-[300px] rounded-lg border border-border bg-background/40 p-3 text-center text-[9px] text-muted-foreground">Research presentation layer · anonymized dataset IDs</div>
    </section>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="panel rounded-xl p-4"><div className="mb-2 flex items-center gap-2 text-[10px] font-bold text-primary"><ShieldCheck size={14}/> Structured data inputs</div><div className="flex flex-wrap gap-2">{svmInputs.map(x=><span key={x} className="rounded-md bg-secondary px-2.5 py-1.5 font-mono-data text-[9px] text-foreground">{x}</span>)}</div><p className="mt-3 text-[9px] text-muted-foreground">Historical injury is contextual report information, never an SVM feature.</p></div><div className="panel rounded-xl p-4"><div className="mb-2 flex items-center gap-2 text-[10px] font-bold text-[#87b5c8]"><Video size={14}/> Movement feature outputs</div><div className="flex flex-wrap gap-2">{poseFeatures.map(x=><span key={x} className="rounded-md bg-secondary px-2.5 py-1.5 text-[9px] text-foreground">{x}</span>)}</div><p className="mt-3 text-[9px] text-muted-foreground">Pose features belong to the computer-vision branch, not the current SVM.</p></div></div>
  </div>;
}

export function MethodologyPage() {
  return <div><PageIntro eyebrow="Research protocol / workflow" title="Methodology" description="The project combines a structured-data screening workflow and an independent computer-vision movement workflow." />
    <div className="relative"><div className="absolute bottom-10 left-[19px] top-8 hidden w-px bg-border sm:block"/><div className="space-y-3">{methodology.map((item,i)=><article className="panel relative grid gap-3 rounded-xl p-4 sm:grid-cols-[42px_1fr] sm:gap-4 sm:p-5" key={item.title} data-testid={`methodology-step-${i+1}`}><div className="relative z-10 flex h-9 w-9 items-center justify-center rounded-lg border border-primary/20 bg-[#16251f] font-mono-data text-[10px] text-primary">{String(i+1).padStart(2,'0')}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-[12px] font-bold">{item.title}</h3>{i===1||i===2||i===3?<span className="rounded bg-[#6a9bb0]/10 px-1.5 py-1 text-[8px] font-bold text-[#87b5c8]">COMPUTER VISION</span>:null}{i===5||i===7?<span className="rounded bg-primary/10 px-1.5 py-1 text-[8px] font-bold text-primary">STRUCTURED DATA</span>:null}</div><p className="mt-1.5 text-[10px] leading-5 text-muted-foreground">{item.description}</p><div className="mt-2 rounded-md bg-background/55 px-2.5 py-2 text-[9px] leading-5 text-foreground/80">{item.detail}</div></div></article>)}</div></div>
    <div className="mt-5 grid gap-4 md:grid-cols-2"><div className="panel rounded-xl p-5"><div className="mb-3 text-[10px] font-bold text-foreground">Structured screening inputs</div><div className="space-y-2">{svmInputs.map((f,i)=><div key={f} className="flex items-center justify-between rounded-lg bg-background/45 px-3 py-2.5"><span className="font-mono-data text-[9px] text-primary">{f}</span><span className="text-[8px] text-muted-foreground">SVM input {i+1}</span></div>)}</div><div className="mt-3 text-[9px] leading-5 text-muted-foreground">Previous injury is contextual in individual reports and not an input feature.</div></div><div className="panel rounded-xl p-5"><div className="mb-3 text-[10px] font-bold text-foreground">Interpretation</div><p className="text-[10px] leading-6 text-muted-foreground">The SVM is reported as the high-sensitivity screening candidate based on the supplied model comparison. The computer-vision branch describes detection and movement features; it does not output injury probability.</p><div className="mt-3"><Disclaimer /></div></div></div>
  </div>;
}
